"""init

Revision ID: 03a7f0ead8f9
Revises: 
Create Date: 2025-06-16 00:06:23.670029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03a7f0ead8f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_number', sa.String(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_number', sa.String(), nullable=True),
    sa.Column('from_station', sa.String(), nullable=True),
    sa.Column('to_station', sa.String(), nullable=True),
    sa.Column('current_station', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('operation_date', sa.String(), nullable=True),
    sa.Column('waybill', sa.String(), nullable=True),
    sa.Column('km_left', sa.Integer(), nullable=True),
    sa.Column('forecast_days', sa.Float(), nullable=True),
    sa.Column('wagon_number', sa.String(), nullable=True),
    sa.Column('operation_road', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracking_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('containers', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('notify_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    op.drop_table('tracking_subscriptions')
    op.drop_table('tracking')
    op.drop_table('stats')
    # ### end Alembic commands ###
