"""add_finance_module_full

Revision ID: 44c171840ca0
Revises: a2a1d3e8b4f9
Create Date: 2025-12-08 08:04:09.784330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44c171840ca0'
down_revision: Union[str, None] = 'a2a1d3e8b4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculation_items')
    op.drop_table('system_settings')
    op.drop_table('container_finances')
    op.drop_index(op.f('ix_calculations_service_provider'), table_name='calculations')
    op.drop_index(op.f('ix_calculations_title'), table_name='calculations')
    op.drop_table('calculations')
    op.drop_index(op.f('ix_rail_tariff_rates_station_from_code'), table_name='rail_tariff_rates')
    op.drop_index(op.f('ix_rail_tariff_rates_station_to_code'), table_name='rail_tariff_rates')
    op.drop_table('rail_tariff_rates')
    op.add_column('terminal_containers', sa.Column('weight_brutto', sa.Float(), nullable=True))
    op.add_column('terminal_containers', sa.Column('weight_netto', sa.Float(), nullable=True))
    op.add_column('trains', sa.Column('service_provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trains', 'service_provider')
    op.drop_column('terminal_containers', 'weight_netto')
    op.drop_column('terminal_containers', 'weight_brutto')
    op.create_table('rail_tariff_rates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('station_from_code', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('station_to_code', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('container_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('rate_no_vat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('rail_tariff_rates_pkey')),
    sa.UniqueConstraint('station_from_code', 'station_to_code', 'container_type', name=op.f('uq_tariff_route_type'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_rail_tariff_rates_station_to_code'), 'rail_tariff_rates', ['station_to_code'], unique=False)
    op.create_index(op.f('ix_rail_tariff_rates_station_from_code'), 'rail_tariff_rates', ['station_from_code'], unique=False)
    op.create_table('calculations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('calculations_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('service_provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('service_type', postgresql.ENUM('TRAIN', 'SINGLE', name='servicetype'), autoincrement=False, nullable=False),
    sa.Column('wagon_type', postgresql.ENUM('PLATFORM', 'GONDOLA', name='wagontype'), autoincrement=False, nullable=False),
    sa.Column('container_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('station_from', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('station_to', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('valid_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('valid_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('margin_type', postgresql.ENUM('FIX', 'PERCENT', name='margintype'), autoincrement=False, nullable=False),
    sa.Column('margin_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_price_netto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('vat_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED', name='calculationstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='calculations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_calculations_title'), 'calculations', ['title'], unique=False)
    op.create_index(op.f('ix_calculations_service_provider'), 'calculations', ['service_provider'], unique=False)
    op.create_table('container_finances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('terminal_container_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_calculation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sales_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('extra_expenses', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('margin_abs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_calculation_id'], ['calculations.id'], name=op.f('container_finances_source_calculation_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['terminal_container_id'], ['terminal_containers.id'], name=op.f('container_finances_terminal_container_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('container_finances_pkey')),
    sa.UniqueConstraint('terminal_container_id', name=op.f('container_finances_terminal_container_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('system_settings',
    sa.Column('key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('system_settings_pkey'))
    )
    op.create_table('calculation_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('calculation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cost_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_auto_calculated', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculations.id'], name=op.f('calculation_items_calculation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('calculation_items_pkey'))
    )
    # ### end Alembic commands ###
