"""add_finance_module

Revision ID: 5a052cd4819d
Revises: a2a1d3e8b4f9
Create Date: 2025-12-07 23:33:13.993064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a052cd4819d'
down_revision: Union[str, None] = 'a2a1d3e8b4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terminal_containers', sa.Column('weight_brutto', sa.Float(), nullable=True))
    op.add_column('terminal_containers', sa.Column('weight_netto', sa.Float(), nullable=True))
    op.add_column('trains', sa.Column('service_provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trains', 'service_provider')
    op.drop_column('terminal_containers', 'weight_netto')
    op.drop_column('terminal_containers', 'weight_brutto')
    # ### end Alembic commands ###
