"""add_missing_cols

Revision ID: 77a802e2957e
Revises: 
Create Date: 2025-12-11 01:49:11.740222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a802e2957e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'container_finances', 'terminal_containers', ['terminal_container_id'], ['id'], ondelete='CASCADE')
    op.add_column('terminal_containers', sa.Column('inn', sa.String(), nullable=True))
    op.add_column('terminal_containers', sa.Column('short_name', sa.String(), nullable=True))
    op.add_column('terminal_containers', sa.Column('manufacture_year', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terminal_containers', 'manufacture_year')
    op.drop_column('terminal_containers', 'short_name')
    op.drop_column('terminal_containers', 'inn')
    op.drop_constraint(None, 'container_finances', type_='foreignkey')
    # ### end Alembic commands ###
