"""init_full_schema

Revision ID: 7f41be8e75b4
Revises: 
Create Date: 2025-12-11 02:17:13.079749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f41be8e75b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terminal_containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_number', sa.String(length=11), nullable=False),
    sa.Column('terminal', sa.String(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('inn', sa.String(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('stock', sa.String(), nullable=True),
    sa.Column('customs_mode', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('container_type', sa.String(length=20), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('payload', sa.Float(), nullable=True),
    sa.Column('tare', sa.Float(), nullable=True),
    sa.Column('manufacture_year', sa.String(), nullable=True),
    sa.Column('weight_client', sa.Float(), nullable=True),
    sa.Column('weight_terminal', sa.Float(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('temperature', sa.String(), nullable=True),
    sa.Column('seals', sa.String(), nullable=True),
    sa.Column('accept_date', sa.Date(), nullable=True),
    sa.Column('accept_time', sa.Time(), nullable=True),
    sa.Column('in_id', sa.String(), nullable=True),
    sa.Column('in_transport', sa.String(), nullable=True),
    sa.Column('in_number', sa.String(), nullable=True),
    sa.Column('in_driver', sa.String(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('train', sa.String(), nullable=True),
    sa.Column('dispatch_date', sa.Date(), nullable=True),
    sa.Column('dispatch_time', sa.Time(), nullable=True),
    sa.Column('out_id', sa.String(), nullable=True),
    sa.Column('out_transport', sa.String(), nullable=True),
    sa.Column('out_number', sa.String(), nullable=True),
    sa.Column('out_driver', sa.String(), nullable=True),
    sa.Column('release', sa.String(), nullable=True),
    sa.Column('carrier', sa.String(), nullable=True),
    sa.Column('manager', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('weight_netto', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terminal_containers_container_number'), 'terminal_containers', ['container_number'], unique=True)
    op.create_index(op.f('ix_terminal_containers_train'), 'terminal_containers', ['train'], unique=False)
    op.create_foreign_key(None, 'container_finances', 'terminal_containers', ['terminal_container_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'container_finances', type_='foreignkey')
    op.drop_index(op.f('ix_terminal_containers_train'), table_name='terminal_containers')
    op.drop_index(op.f('ix_terminal_containers_container_number'), table_name='terminal_containers')
    op.drop_table('terminal_containers')
    # ### end Alembic commands ###
