"""add event alert rules table

Revision ID: a2a1d3e8b4f9
Revises: 3045d82ec1ca
Create Date: 2025-11-12 15:10:21.525338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a1d3e8b4f9'
down_revision: Union[str, None] = '3045d82ec1ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=True),
    sa.Column('recipient_user_id', sa.BigInteger(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.telegram_id'], name=op.f('fk_event_alert_rules_recipient_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_event_alert_rules_subscription_id_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_alert_rules'))
    )
    op.create_index(op.f('ix_event_alert_rules_channel'), 'event_alert_rules', ['channel'], unique=False)
    op.create_index(op.f('ix_event_alert_rules_event_type'), 'event_alert_rules', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_alert_rules_event_type'), table_name='event_alert_rules')
    op.drop_index(op.f('ix_event_alert_rules_channel'), table_name='event_alert_rules')
    op.drop_table('event_alert_rules')
    # ### end Alembic commands ###
