# .github/workflows/deploy.yml

name: Deploy to Server

on:
  push:
    branches:
      - main # Убедитесь, что это ваша основная ветка (может быть 'master')

jobs:
  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Получаем код из репозитория
    - name: Checkout repository
      uses: actions/checkout@v4

    # Шаг 2: Подключаемся к серверу и выполняем команды
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        script: |
          # Устанавливаем флаг, чтобы скрипт завершился при первой ошибке
          set -e

          echo "--- Перехожу в директорию проекта ---"
          cd /root/zdtarif_bot

          echo "--- Проверяю статус Git перед обновлением ---"
          git status

          echo "--- Загружаю последние изменения из ветки main ---"
          git pull origin main

          echo "--- Активирую виртуальное окружение ---"
          source venv/bin/activate

          echo "--- Устанавливаю/обновляю зависимости ---"
          pip install -r requirements.txt

          echo "--- Перезапускаю сервис systemd ---"
          sudo systemctl restart zdtarif_bot.service

          echo "--- Деплой успешно завершен! ---"